drop table if exists SYSTEM_ITEM;

CREATE TABLE SYSTEM_ITEM
(
    ID          VARCHAR PRIMARY KEY,
    URL         VARCHAR,
    MODIFIED_AT VARCHAR NOT NULL,
    PARENT_ID   VARCHAR,
    ITEM_TYPE   VARCHAR NOT NULL,
    ITEM_SIZE   INT
);

drop table if exists MOD_ITEM;

CREATE TABLE MOD_ITEM
(
    MODIFIED_AT      TIMESTAMP NOT NULL,
    MODIFIED_ITEM_ID VARCHAR   NOT NULL,
    PRIMARY KEY (MODIFIED_AT, MODIFIED_ITEM_ID)
);

drop table if exists HISTORY_ITEM;
drop sequence SEQ_HISTORY_ITEM;

CREATE SEQUENCE SEQ_HISTORY_ITEM;

CREATE TABLE HISTORY_ITEM
(
    ID          BIGINT DEFAULT NEXT VALUE FOR SEQ_HISTORY_ITEM PRIMARY KEY,
    ITEM_ID     VARCHAR   NOT NULL,
    DATE        VARCHAR   NOT NULL,
    URL         VARCHAR,
    PARENT_ID   VARCHAR,
    ITEM_SIZE   INT,
    ITEM_TYPE   VARCHAR   NOT NULL,
    MODIFIED_AT TIMESTAMP NOT NULL
);
