drop table if exists SYSTEM_ITEM;

CREATE TABLE SYSTEM_ITEM
(
    ID          VARCHAR PRIMARY KEY,
    URL         VARCHAR,
    MODIFIED_AT VARCHAR NOT NULL,
    PARENT_ID   VARCHAR,
    ITEM_TYPE   VARCHAR NOT NULL,
    ITEM_SIZE   INT
);

drop table if exists MOD_ITEM;

CREATE TABLE MOD_ITEM
(
    MODIFIED_AT      TIMESTAMP NOT NULL,
    MODIFIED_ITEM_ID VARCHAR   NOT NULL,
    PRIMARY KEY (MODIFIED_AT, MODIFIED_ITEM_ID)
);
