server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
  address: 0.0.0.0
spring:
  application:
    name: cloudstore-app
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DB_ADDR:localhost}:5432/cloudstore-db
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:postgres}
      maximum-pool-size: 5
      connection-test-query: "SELECT 1"
      pool-name: cloudStorePool
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  cache:
    jcache:
      config: classpath:echache.xml
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: imports/
      rate-limits:
        - bandwidths:
            - capacity: 1000
              time: 1
              unit: minutes
    - http-response-body:
        message=Too many requests
management:
  endpoints:
    web:
      exposure:
        include: 'beans,health'

  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  level:
    root: INFO
    org.springframework: DEBUG
    ru.aasmc.cloudstore: DEBUG

