server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
  address: 0.0.0.0
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      maximum-pool-size: 5
      connection-test-query: "SELECT 1"
      pool-name: cloudStorePool
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  cache:
    jcache:
      config: classpath:echache.xml
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /imports
      rate-limits:
        - bandwidths:
            - capacity: 1000
              time: 1
              unit: minutes
    - http-response-body:
        message=Too many requests
management:
  endpoints:
    web:
      exposure:
        include: 'beans,health'

  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  level:
    root: INFO
    org.springframework: DEBUG
    ru.aasmc.cloudstore: DEBUG
