version: "3.8"
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:14.5
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./volume/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "cloudstore-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  cloudstore:
    build: ../docker-image/
    image: cloudstore-app:latest
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_ADDR: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  pg-data: